version: "3"
services:  
  db: 
    image: mysql:8.0
    env_file: .env
    container_name: mysql
    volumes:
      - db:/var/lib/mysql # 永続化時のマウントボリュームdir
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - ${DB_PORT}:3306
    tty: true
    expose: 
      - ${DB_PORT}
      - 3306
    
  nginx:
    image: mysql:8.0
    env_file: .env
    container_name: nginx
    
    ports: 
        - 8080:80
    volumes: 
        - .nginx/default.conf:/etc/nginx/conf.d/default.conf
    # links を設定しておけば、以下のエイリアスとportの指定でdb接続が可能。
    links: 
        - db
    tty: true
    depends_on: 
        - db

  redis:
    image: redis:latest
    container_name: redis #下記のコマンド時に使用するコンテナ名
    ports:
      - "6379:6379" #redisのデフォルトのポートは6379
    volumes:
      - "./data/redis:/data"

    

# 永続化時のマウントボリュームdir
volumes:
  db: 

